@echo off
setlocal

echo ==========================================
echo      TaskSystem Build Script
echo ==========================================

:: 1. Prepare directories
if not exist "external" (
    echo [INFO] Creating external directory...
    mkdir "external"
)

if not exist "build" (
    echo [INFO] Creating build directory...
    mkdir "build"
)

cd build

:: 2. Configure CMake
:: Specify Visual Studio 2019 generator
echo [INFO] Configuring project for Visual Studio 2019...
cmake .. -G "Visual Studio 16 2019" -A x64
if %errorlevel% neq 0 goto :error

:: 3. Build project (Debug configuration)
echo [INFO] Building project...
cmake --build . --config Debug
if %errorlevel% neq 0 goto :error

:: Build example code
echo [INFO] Building examples...
cmake --build . --target example --config Debug
if %errorlevel% neq 0 goto :error

:: Build benchmark code
echo [INFO] Building benchmarks...
cmake --build . --target benchmark --config Debug
if %errorlevel% neq 0 goto :error

:: 4. Run unit tests
echo [INFO] Running Unit Tests...
:: -C Debug specifies configuration, --output-on-failure outputs detailed information on failure
ctest -C Debug --output-on-failure
if %errorlevel% neq 0 goto :error

:: 5. Run example program
echo [INFO] Running Example...
:: Executables generated by Visual Studio are usually located in the Debug subdirectory, named example.exe
if exist "Debug\example.exe" (
    "Debug\example.exe"
) else if exist "examples\Debug\example.exe" (
    "examples\Debug\example.exe"
) else (
    echo [WARN] Example executable not found in expected paths.
)

:: 6. Run benchmark program
echo [INFO] Running Benchmark...
if exist "Debug\benchmark.exe" (
    "Debug\benchmark.exe"
) else if exist "benchmarks\Debug\benchmark.exe" (
    "benchmarks\Debug\benchmark.exe"
) else (
    echo [WARN] Benchmark executable not found in expected paths.
)

echo ==========================================
echo      Build and Run Successful!
echo ==========================================
cd ..
exit /b 0

:error
echo [ERROR] An error occurred during the build process.
cd ..
exit /b 1