from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
from conan.tools.files import copy, rmdir
from conan.tools.build import check_min_cppstd
import os

required_conan_version = ">=1.53.0"

class TaskEngineConan(ConanFile):
    name = "task-engine"
    version = "1.0.0"
    description = "A high-performance, thread-safe C++17 Task Execution Module."
    license = "MIT"
    url = "https://github.com/YourUsername/TaskSystem"
    homepage = "https://github.com/YourUsername/TaskSystem"
    topics = ("threading", "task-system", "cpp17", "threadpool")
    package_type = "library"
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
    }

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self)

    def validate(self):
        if self.settings.compiler.get_safe("cppstd"):
            check_min_cppstd(self, 17)

    def generate(self):
        tc = CMakeToolchain(self)
        # Disable tests and examples for the package build to save time
        tc.variables["TASK_ENGINE_BUILD_TESTS"] = False
        tc.variables["TASK_ENGINE_BUILD_EXAMPLES"] = False
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        copy(self, "LICENSE", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
        cmake = CMake(self)
        cmake.install()
        # Remove CMake config files generated by the project; Conan handles this via package_info
        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))

    def package_info(self):
        self.cpp_info.libs = ["task_engine"]
        self.cpp_info.set_property("cmake_file_name", "TaskEngine")
        self.cpp_info.set_property("cmake_target_name", "task_engine::task_engine")

        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs.append("pthread")