name: Vcpkg CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure git history is available for versioning

    - name: Restore vcpkg binary cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Configure CMake
      # We use the pre-installed vcpkg toolchain and enable the 'tests' feature defined in vcpkg.json
      run: >
        cmake -B build -S .
        -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake
        -DVCPKG_MANIFEST_FEATURES=tests
        -DTASK_ENGINE_BUILD_TESTS=ON
        -DTASK_ENGINE_BUILD_EXAMPLES=ON
      env:
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    - name: Build TaskEngine
      run: cmake --build build --config Release

    - name: Run Tests
      shell: bash
      run: |
        cd build
        ctest -C Release --output-on-failure

    - name: List installed files (for verification)
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        ls -R instdir || dir /s instdir
    - name: Package
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        cmake --install build --config Release --prefix instdir
        ASSET_PREFIX="TaskEngine-${{ github.ref_name }}-${{ matrix.os }}"
        if [ "${{ runner.os }}" == "Windows" ]; then
          7z a "${ASSET_PREFIX}.zip" ./instdir/*
        else
          tar -czvf "${ASSET_PREFIX}.tar.gz" -C instdir .
        fi

    - name: Upload Artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: TaskEngine-*

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binary-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          files: TaskEngine-*